kind: Deployment
apiVersion: apps/v1
metadata:
  name: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - name: search
        image: docker.io/ksanas/foodie-search:v1
        imagePullPolicy: Always
        stdin: true
        tty: true
        ports:
        - containerPort: 5000
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: search
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 31500
  selector:
    app: search  