kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: docker.io/ksanas/foodie-mongo:v1
        imagePullPolicy: Always
        stdin: true
        tty: true
        ports:
        - containerPort: 27017
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: mongo
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      nodePort: 32500
  selector:
    app: mongo  